cleanup, usage of --os arg

diff --git a/aliases-init b/aliases-init
--- a/aliases-init
+++ b/aliases-init
@@ -1,16 +1,41 @@
 #!/bin/bash
-#### Adds line to source custom alias generation file
-__aliases-init-func () {
-	local SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
-	local ALIASES_SRC=aliases-source
-	local LINE='[ -f '"${SCRIPTPATH}"'/'"${ALIASES_SRC}"' ] && . '"${SCRIPTPATH}"/"${ALIASES_SRC}"
-	local FILE=~/.bash_aliases
-	#### add line to FILE if needed to source ALIASES_SRC
-	if [ ! -f "${FILE}" ]; then
-		echo "${FILE}" does not exist, creating... ; touch "${FILE}"
-	fi
-	grep -qF -- "${LINE}" "${FILE}" || (echo -e "\n${LINE}" >> "${FILE}" && echo "${ALIASES_SRC}" added to "${FILE}") || return 1
+#
+# description: adds line to source alias-source bash_aliases
+
+__parse_script_arguments() {
+    while (( "${#}" )); do
+        case "${1}" in
+            --operating-system|--os)
+				[ "${2}" != 'linux' ] && [ "${2}" != 'windows' ] && [ "${2}" != 'wsl' ] && echo "ERROR: unrecognized ${1} parameter ${2}" && return 1
+                operating_sys="${2}"
+                shift
+				;;
+            *)
+                echo "ERROR: arg ${1} is unexpected" && return 2
+                ;;
+        esac
+        shift
+    done
 }
-####
-__aliases-init-func
-exit "${?}"
+
+_aliases_init () {
+	## default values
+	local operating_sys=''
+    ## fill script vars with cmd line args and/or default values where applicable
+    __parse_script_arguments "${@}" || return "1${?}"
+	## create arg lists for source script
+	local args="--os ${operating_sys}"
+	## hardcoded values
+	local script_path="${BASH_SOURCE[0]}"
+	local script_dir="$(cd "$(dirname "${script_path}")"; pwd -P)"
+	local aliases_src='aliases-source'
+	local line='[ -f '"${script_dir}/${aliases_src}"' ] && source '"${script_dir}/${aliases_src} ${args}"
+	local bashrc="${HOME}/.bashrc"
+	local bash_aliases="${HOME}/.bash_aliases"
+	#### add line to $bash_aliases if needed to source $aliases_src
+	[ ! -f "${bashrc}" ] && { echo "NOTE: ${bashrc} does not exist, creating..."; touch "${bashrc}" && echo "source ${bash_aliases}" > "${bashrc}"; }
+	[ ! -f "${bash_aliases}" ] && echo "NOTE: ${bash_aliases}" does not exist, creating... && touch "${bash_aliases}"
+	grep -qF -- "${line}" "${bash_aliases}" || (echo >> "${bash_aliases}" && echo "${line}" >> "${bash_aliases}" && echo "NOTE: ${aliases_src}" added to "${bash_aliases}") || return 1
+}
+
+_aliases_init "${@}" || exit "${?}"
diff --git a/aliases-source b/aliases-source
--- a/aliases-source
+++ b/aliases-source
@@ -1,51 +1,61 @@
 #!/bin/bash
-######### This file is sourced via the aliases-init script
-is_git_dirty() { if [[ $(git diff --shortstat 2> /dev/null | tail -n1) != "" ]]; then return 1; else return 0; fi } # unused
-alias gitdirty='is_git_dirty; if [ $? -eq 1 ]; then echo 1; else echo 0; fi' # unused
-cd_parent_aliases() { local ALS='.'; local DIR; for VAR in {1..10} ; do ALS="${ALS}."; DIR="${DIR}../"; alias "${ALS}"'=cd '"${DIR}"; done }
-######### git  #########
-alias gg='git status -sb'
-alias gc='git checkout'
-alias gcm='git checkout master'
-alias gp='git pull'
-alias gcp='git cherry-pick'
-alias gcmp='git checkout master && git pull'
-alias grm='git fetch && git rebase origin/master'
-alias ggg='git submodule foreach git status -sb'
-alias gsu='git submodule update'
-alias gss='git submodule status'
-alias lg='git log --date=format:"%d-%m-%Y %H:%M" --pretty=format:"%h%x20%x20%Cred%ad%x20%x20%Cblue%an%x20%x20%Creset%s"'
-alias log='git log --graph --abbrev-commit --decorate --format=format:"%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset) %C(bold cyan)(committed: %cD)%C(reset) %C(auto)%d%C(reset)%n''          %C(white)%s%C(reset)%n''          %C(dim white)- %an <%ae> %C(reset) %C(dim white)(committer: %cn <%ce>)%C(reset)"'
-######### ide  #########
-alias vs='code .'
-######### misc #########
-alias op='xdg-open'
-alias rc='xdg-open ~/.bashrc'
-alias rca='xdg-open ~/.bash_aliases'
-alias rcg='xdg-open ~/gene-ws/aliases/aliases-source' # TODO: undo relative path to ws
-alias rcs='source ~/.bashrc'
-alias rcas='source ~/.bash_aliases'
-alias rcgs='source ~/gene-ws/aliases/aliases-source'
-alias sudo='sudo ' # purpose is to allow 'sudo <alias>'
-alias ch='chmod 755'
-alias rs='reset'
-######### dirs #########
-alias dl='cd ~/Downloads'
-alias dsk='cd ~/Desktop'
-alias doc='cd ~/Documents'
-alias ~='cd ~'
-cd_parent_aliases
-#### Completion Aid # TODO make this less of a relative path. Return error if doesnt exist
-git-completion-source(){
-	local DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
-	local git_completion_dir=$(find "$(dirname "$DIR")"/third-party/ -name git-completion[.^]bash)
-	if [ -f "$git_completion_dir" ]; then
-	  . "$git_completion_dir"
-	  __git_complete gp _git_pull
-	  __git_complete gc _git_checkout
-	  __git_complete gcp _git_cherry_pick
-	  __git_complete git _git
-	fi
+#
+# description: this file is sourced via the aliases-init script
+
+__parse_script_arguments() {
+    while (( "${#}" )); do
+        case "${1}" in
+            --operating-system|--os)
+				[ "${2}" != 'linux' ] && [ "${2}" != 'windows' ] && [ "${2}" != 'wsl' ] && echo "ERROR: unrecognized ${1} parameter ${2}" && return 1
+                operating_sys="${2}"
+                shift
+				;;
+            *)
+                echo "ERROR: arg ${1} is unexpected" && return 2
+                ;;
+        esac
+        shift
+    done
 }
 
-#git-completion-source # TODO: investigate git completion problems
+_aliases_source(){
+	## default values
+	local operating_sys=''
+    ## fill script vars with cmd line args and/or default values where applicable
+    __parse_script_arguments "${@}" || return "1${?}"
+	## hardcoded values
+	local script_path="${BASH_SOURCE[0]}"
+	######### cfg  #########
+	local open=''; { [ "${operating_sys}" == 'linux' ] && open='xdg-open'; } || { [ "${operating_sys}" == 'windows' ] && open='start'; } || { [ "${operating_sys}" == 'wsl' ] && open='wsl-open'; } || ! echo "ERROR: unable to set open var" || return 1
+	######### func #########
+	cd_parent_aliases() { local ALS='.'; local DIR; for VAR in {1..10} ; do ALS="${ALS}."; DIR="${DIR}../"; alias "${ALS}"'=cd '"${DIR}"; done }
+	######### git  #########
+	alias gg='git status -sb'
+	alias gc='git checkout'
+	alias gcm='git checkout master'
+	alias gf='git fetch'
+	alias gp='git pull'
+	alias grom='git fetch && git rebase origin/master'
+	alias lg='git log --date=format:"%d-%m-%Y %H:%M" --pretty=format:"%h%x20%x20%Cred%ad%x20%x20%Cblue%an%x20%x20%Creset%s"'
+	alias log='git log --graph --abbrev-commit --decorate --format=format:"%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset) %C(bold cyan)(committed: %cD)%C(reset) %C(auto)%d%C(reset)%n''          %C(white)%s%C(reset)%n''          %C(dim white)- %an <%ae> %C(reset) %C(dim white)(committer: %cn <%ce>)%C(reset)"'
+	alias ggg='git submodule foreach git status -sb'
+	alias gsu='git submodule update'
+	alias gss='git submodule status'
+	######### dirs #########
+	cd_parent_aliases
+	alias dl="cd ${HOME}/Downloads"
+	alias dsk="cd ${HOME}/Desktop"
+	alias doc="cd ${HOME}/Documents"
+	######### misc #########
+	alias op="${open}"
+	alias rc="${open} ${HOME}/.bashrc"
+	alias rca="${open} ${HOME}/.bash_aliases"
+	alias rcg="${open} ${script_path}"
+	alias rcs="source ${HOME}/.bashrc"
+	alias rcas="source ${HOME}/.bash_aliases"
+	alias rcgs="source ${script_path}"
+	[ "${operating_sys}" == 'windows' ] || alias sudo='sudo ' # purpose is to allow 'sudo <alias>'
+	alias rs='reset'
+}
+
+_aliases_source "${@}" || exit "${?}"
